/*
 * This file was automatically generated by EvoSuite
 * Sun Nov 03 21:28:38 GMT 2019
 */

package tutorial;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import tutorial.Node;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Node_ESTest extends Node_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Node<String> node0 = new Node<String>("1o:1\"");
      Node<String> node1 = new Node<String>((String) null);
      node0.setNext(node1);
      assertFalse(node0.equals((Object)node1));
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Node<String> node0 = new Node<String>((String) null);
      String string0 = node0.getObject();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Node<String> node0 = new Node<String>("1o:1\"");
      node0.setNext(node0);
      Node<String> node1 = node0.getNext();
      assertSame(node1, node0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Node<String> node0 = new Node<String>("1o:1\"");
      String string0 = node0.getObject();
      assertEquals("1o:1\"", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Node<String> node0 = new Node<String>("1o:1\"");
      Node<String> node1 = node0.getNext();
      assertNull(node1);
  }
}
